# Generated by Django 5.1.6 on 2025-09-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_supply'),
        ('transactions', '0004_supplyhistory'),
    ]

    operations = [
    ]
