# Generated by Django 5.1.6 on 2025-10-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_inventory_alter_payment_amount_and_more'),
        ('transactions', '0005_merge_0002_delete_supply_0004_supplyhistory'),
    ]

    operations = [
    ]
