# Generated by Django 5.2.5 on 2025-09-02 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_balance', models.DecimalField(decimal_places=2, default=0, help_text='Credit sales added today', max_digits=12)),
                ('wholesale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retail_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('daily_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date', 'id')},
            },
        ),
    ]
